// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (
    id, email, password_hash, status, display_name, two_factor_enabled, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now(), now()
) RETURNING id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret
`

type CreateAdminParams struct {
	ID               pgtype.UUID `json:"id"`
	Email            string      `json:"email"`
	PasswordHash     string      `json:"password_hash"`
	Status           string      `json:"status"`
	DisplayName      pgtype.Text `json:"display_name"`
	TwoFactorEnabled bool        `json:"two_factor_enabled"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admins, error) {
	row := q.db.QueryRow(ctx, createAdmin,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Status,
		arg.DisplayName,
		arg.TwoFactorEnabled,
	)
	var i Admins
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorSecret,
	)
	return i, err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret FROM admins
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (Admins, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i Admins
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorSecret,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret FROM admins
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAdminByID(ctx context.Context, id pgtype.UUID) (Admins, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i Admins
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorSecret,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret FROM admins
ORDER BY created_at DESC
`

func (q *Queries) ListAdmins(ctx context.Context) ([]Admins, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Admins
	for rows.Next() {
		var i Admins
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Status,
			&i.DisplayName,
			&i.TwoFactorEnabled,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TwoFactorSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminLastLogin = `-- name: UpdateAdminLastLogin :exec
UPDATE admins
SET last_login_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateAdminLastLogin(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateAdminLastLogin, id)
	return err
}

const updateAdminStatus = `-- name: UpdateAdminStatus :one
UPDATE admins
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, password_hash, status, display_name, two_factor_enabled, last_login_at, created_at, updated_at, two_factor_secret
`

type UpdateAdminStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAdminStatus(ctx context.Context, arg UpdateAdminStatusParams) (Admins, error) {
	row := q.db.QueryRow(ctx, updateAdminStatus, arg.ID, arg.Status)
	var i Admins
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.DisplayName,
		&i.TwoFactorEnabled,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TwoFactorSecret,
	)
	return i, err
}

const updateAdminTwoFactor = `-- name: UpdateAdminTwoFactor :exec
UPDATE admins
SET two_factor_enabled = $2, two_factor_secret = $3, updated_at = now()
WHERE id = $1
`

type UpdateAdminTwoFactorParams struct {
	ID               pgtype.UUID `json:"id"`
	TwoFactorEnabled bool        `json:"two_factor_enabled"`
	TwoFactorSecret  pgtype.Text `json:"two_factor_secret"`
}

func (q *Queries) UpdateAdminTwoFactor(ctx context.Context, arg UpdateAdminTwoFactorParams) error {
	_, err := q.db.Exec(ctx, updateAdminTwoFactor, arg.ID, arg.TwoFactorEnabled, arg.TwoFactorSecret)
	return err
}
