// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditEvent = `-- name: CreateAuditEvent :one
INSERT INTO audit_events (
    id, actor_type, actor_id, action, resource_type, resource_id,
    before_data, after_data, ip_address, user_agent, request_id, trace_id, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, now()
) RETURNING id, actor_type, actor_id, action, resource_type, resource_id, before_data, after_data, ip_address, user_agent, request_id, trace_id, created_at
`

type CreateAuditEventParams struct {
	ID           pgtype.UUID `json:"id"`
	ActorType    string      `json:"actor_type"`
	ActorID      pgtype.UUID `json:"actor_id"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	BeforeData   []byte      `json:"before_data"`
	AfterData    []byte      `json:"after_data"`
	IpAddress    *netip.Addr `json:"ip_address"`
	UserAgent    pgtype.Text `json:"user_agent"`
	RequestID    pgtype.Text `json:"request_id"`
	TraceID      pgtype.Text `json:"trace_id"`
}

func (q *Queries) CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvents, error) {
	row := q.db.QueryRow(ctx, createAuditEvent,
		arg.ID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.BeforeData,
		arg.AfterData,
		arg.IpAddress,
		arg.UserAgent,
		arg.RequestID,
		arg.TraceID,
	)
	var i AuditEvents
	err := row.Scan(
		&i.ID,
		&i.ActorType,
		&i.ActorID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.BeforeData,
		&i.AfterData,
		&i.IpAddress,
		&i.UserAgent,
		&i.RequestID,
		&i.TraceID,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_type, actor_id, action, resource_type, resource_id, before_data, after_data, ip_address, user_agent, request_id, trace_id, created_at FROM audit_events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAuditEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvents, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvents
	for rows.Next() {
		var i AuditEvents
		if err := rows.Scan(
			&i.ID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.BeforeData,
			&i.AfterData,
			&i.IpAddress,
			&i.UserAgent,
			&i.RequestID,
			&i.TraceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
