// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instances.sql

package repository

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (
  id, subscription_id, node_id, provider_id, provider_instance_id, name,
  desired_state, observed_state, cpu_cores, memory_mb, disk_gb,
  traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6,
  version, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6,
  $7, $8, $9, $10, $11,
  $12, $13, $14, $15, $16,
  1, now(), now()
)
RETURNING id, subscription_id, node_id, provider_id, provider_instance_id, name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb, traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6, last_synced_at, version, created_at, updated_at, deleted_at
`

type CreateInstanceParams struct {
	ID                 pgtype.UUID    `json:"id"`
	SubscriptionID     pgtype.UUID    `json:"subscription_id"`
	NodeID             pgtype.UUID    `json:"node_id"`
	ProviderID         pgtype.UUID    `json:"provider_id"`
	ProviderInstanceID pgtype.Text    `json:"provider_instance_id"`
	Name               string         `json:"name"`
	DesiredState       string         `json:"desired_state"`
	ObservedState      string         `json:"observed_state"`
	CpuCores           pgtype.Numeric `json:"cpu_cores"`
	MemoryMb           int32          `json:"memory_mb"`
	DiskGb             int32          `json:"disk_gb"`
	TrafficLimitGb     pgtype.Int8    `json:"traffic_limit_gb"`
	BandwidthMbps      pgtype.Int4    `json:"bandwidth_mbps"`
	ImageID            pgtype.Text    `json:"image_id"`
	PrimaryIpv4        *netip.Addr    `json:"primary_ipv4"`
	PrimaryIpv6        *netip.Addr    `json:"primary_ipv6"`
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instances, error) {
	row := q.db.QueryRow(ctx, createInstance,
		arg.ID,
		arg.SubscriptionID,
		arg.NodeID,
		arg.ProviderID,
		arg.ProviderInstanceID,
		arg.Name,
		arg.DesiredState,
		arg.ObservedState,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.TrafficLimitGb,
		arg.BandwidthMbps,
		arg.ImageID,
		arg.PrimaryIpv4,
		arg.PrimaryIpv6,
	)
	var i Instances
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstanceByID = `-- name: GetInstanceByID :one
SELECT id, subscription_id, node_id, provider_id, provider_instance_id, name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb, traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6, last_synced_at, version, created_at, updated_at, deleted_at FROM instances
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstanceByID(ctx context.Context, id pgtype.UUID) (Instances, error) {
	row := q.db.QueryRow(ctx, getInstanceByID, id)
	var i Instances
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstanceBySubscriptionID = `-- name: GetInstanceBySubscriptionID :one
SELECT id, subscription_id, node_id, provider_id, provider_instance_id, name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb, traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6, last_synced_at, version, created_at, updated_at, deleted_at FROM instances
WHERE subscription_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetInstanceBySubscriptionID(ctx context.Context, subscriptionID pgtype.UUID) (Instances, error) {
	row := q.db.QueryRow(ctx, getInstanceBySubscriptionID, subscriptionID)
	var i Instances
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.NodeID,
		&i.ProviderID,
		&i.ProviderInstanceID,
		&i.Name,
		&i.DesiredState,
		&i.ObservedState,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficLimitGb,
		&i.BandwidthMbps,
		&i.ImageID,
		&i.PrimaryIpv4,
		&i.PrimaryIpv6,
		&i.LastSyncedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listInstances = `-- name: ListInstances :many
SELECT id, subscription_id, node_id, provider_id, provider_instance_id, name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb, traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6, last_synced_at, version, created_at, updated_at, deleted_at FROM instances
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instances, error) {
	rows, err := q.db.Query(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instances
	for rows.Next() {
		var i Instances
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.NodeID,
			&i.ProviderID,
			&i.ProviderInstanceID,
			&i.Name,
			&i.DesiredState,
			&i.ObservedState,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficLimitGb,
			&i.BandwidthMbps,
			&i.ImageID,
			&i.PrimaryIpv4,
			&i.PrimaryIpv6,
			&i.LastSyncedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstancesByNodeID = `-- name: ListInstancesByNodeID :many
SELECT id, subscription_id, node_id, provider_id, provider_instance_id, name, desired_state, observed_state, cpu_cores, memory_mb, disk_gb, traffic_limit_gb, bandwidth_mbps, image_id, primary_ipv4, primary_ipv6, last_synced_at, version, created_at, updated_at, deleted_at FROM instances
WHERE node_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListInstancesByNodeID(ctx context.Context, nodeID pgtype.UUID) ([]Instances, error) {
	rows, err := q.db.Query(ctx, listInstancesByNodeID, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instances
	for rows.Next() {
		var i Instances
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.NodeID,
			&i.ProviderID,
			&i.ProviderInstanceID,
			&i.Name,
			&i.DesiredState,
			&i.ObservedState,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficLimitGb,
			&i.BandwidthMbps,
			&i.ImageID,
			&i.PrimaryIpv4,
			&i.PrimaryIpv6,
			&i.LastSyncedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteInstance = `-- name: SoftDeleteInstance :exec
UPDATE instances
SET deleted_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteInstance(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteInstance, id)
	return err
}

const updateInstanceStates = `-- name: UpdateInstanceStates :exec
UPDATE instances
SET desired_state = $2,
    observed_state = $3,
    provider_instance_id = COALESCE($4, provider_instance_id),
    last_synced_at = now(),
    version = version + 1,
    updated_at = now()
WHERE id = $1
`

type UpdateInstanceStatesParams struct {
	ID                 pgtype.UUID `json:"id"`
	DesiredState       string      `json:"desired_state"`
	ObservedState      string      `json:"observed_state"`
	ProviderInstanceID pgtype.Text `json:"provider_instance_id"`
}

func (q *Queries) UpdateInstanceStates(ctx context.Context, arg UpdateInstanceStatesParams) error {
	_, err := q.db.Exec(ctx, updateInstanceStates,
		arg.ID,
		arg.DesiredState,
		arg.ObservedState,
		arg.ProviderInstanceID,
	)
	return err
}
