// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoices.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    id, invoice_no, user_id, subscription_id, order_id, status,
    amount_minor, currency, due_at, paid_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, now(), now()
) RETURNING id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at
`

type CreateInvoiceParams struct {
	ID             pgtype.UUID        `json:"id"`
	InvoiceNo      string             `json:"invoice_no"`
	UserID         pgtype.UUID        `json:"user_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	OrderID        pgtype.UUID        `json:"order_id"`
	Status         string             `json:"status"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	PaidAt         pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoices, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.ID,
		arg.InvoiceNo,
		arg.UserID,
		arg.SubscriptionID,
		arg.OrderID,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.DueAt,
		arg.PaidAt,
	)
	var i Invoices
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInvoiceItem = `-- name: CreateInvoiceItem :one
INSERT INTO invoice_items (
    id, invoice_id, description_i18n, quantity, unit_amount_minor, total_minor, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now()
) RETURNING id, invoice_id, description_i18n, quantity, unit_amount_minor, total_minor, created_at
`

type CreateInvoiceItemParams struct {
	ID              pgtype.UUID `json:"id"`
	InvoiceID       pgtype.UUID `json:"invoice_id"`
	DescriptionI18n []byte      `json:"description_i18n"`
	Quantity        int32       `json:"quantity"`
	UnitAmountMinor int64       `json:"unit_amount_minor"`
	TotalMinor      int64       `json:"total_minor"`
}

func (q *Queries) CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItems, error) {
	row := q.db.QueryRow(ctx, createInvoiceItem,
		arg.ID,
		arg.InvoiceID,
		arg.DescriptionI18n,
		arg.Quantity,
		arg.UnitAmountMinor,
		arg.TotalMinor,
	)
	var i InvoiceItems
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.DescriptionI18n,
		&i.Quantity,
		&i.UnitAmountMinor,
		&i.TotalMinor,
		&i.CreatedAt,
	)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (Invoices, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoices
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByInvoiceNo = `-- name: GetInvoiceByInvoiceNo :one
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices
WHERE invoice_no = $1 LIMIT 1
`

func (q *Queries) GetInvoiceByInvoiceNo(ctx context.Context, invoiceNo string) (Invoices, error) {
	row := q.db.QueryRow(ctx, getInvoiceByInvoiceNo, invoiceNo)
	var i Invoices
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInvoiceByOrderID = `-- name: GetInvoiceByOrderID :one
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices
WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetInvoiceByOrderID(ctx context.Context, orderID pgtype.UUID) (Invoices, error) {
	row := q.db.QueryRow(ctx, getInvoiceByOrderID, orderID)
	var i Invoices
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllInvoices = `-- name: ListAllInvoices :many
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices
ORDER BY created_at DESC
`

func (q *Queries) ListAllInvoices(ctx context.Context) ([]Invoices, error) {
	rows, err := q.db.Query(ctx, listAllInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoices
	for rows.Next() {
		var i Invoices
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNo,
			&i.UserID,
			&i.SubscriptionID,
			&i.OrderID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.DueAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoiceItemsByInvoiceID = `-- name: ListInvoiceItemsByInvoiceID :many
SELECT id, invoice_id, description_i18n, quantity, unit_amount_minor, total_minor, created_at FROM invoice_items
WHERE invoice_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListInvoiceItemsByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceItems, error) {
	rows, err := q.db.Query(ctx, listInvoiceItemsByInvoiceID, invoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceItems
	for rows.Next() {
		var i InvoiceItems
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.DescriptionI18n,
			&i.Quantity,
			&i.UnitAmountMinor,
			&i.TotalMinor,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByUserID = `-- name: ListInvoicesByUserID :many
SELECT id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at FROM invoices
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByUserID(ctx context.Context, userID pgtype.UUID) ([]Invoices, error) {
	rows, err := q.db.Query(ctx, listInvoicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoices
	for rows.Next() {
		var i Invoices
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNo,
			&i.UserID,
			&i.SubscriptionID,
			&i.OrderID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.DueAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $2,
    paid_at = CASE WHEN $2 = 'paid' THEN now() ELSE paid_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, invoice_no, user_id, subscription_id, order_id, status, amount_minor, currency, due_at, paid_at, created_at, updated_at
`

type UpdateInvoiceStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoices, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoices
	err := row.Scan(
		&i.ID,
		&i.InvoiceNo,
		&i.UserID,
		&i.SubscriptionID,
		&i.OrderID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.DueAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
