// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (
    id, transaction_id, account_type, account_id, direction, amount_minor, currency, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, now()
) RETURNING id, transaction_id, account_type, account_id, direction, amount_minor, currency, created_at
`

type CreateLedgerEntryParams struct {
	ID            pgtype.UUID `json:"id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
	AccountType   string      `json:"account_type"`
	AccountID     pgtype.UUID `json:"account_id"`
	Direction     string      `json:"direction"`
	AmountMinor   int64       `json:"amount_minor"`
	Currency      string      `json:"currency"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntries, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.ID,
		arg.TransactionID,
		arg.AccountType,
		arg.AccountID,
		arg.Direction,
		arg.AmountMinor,
		arg.Currency,
	)
	var i LedgerEntries
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountType,
		&i.AccountID,
		&i.Direction,
		&i.AmountMinor,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const createLedgerTransaction = `-- name: CreateLedgerTransaction :one
INSERT INTO ledger_transactions (
    id, type, reference_type, reference_id, description, created_at
) VALUES (
    $1, $2, $3, $4, $5, now()
) RETURNING id, type, reference_type, reference_id, description, created_at
`

type CreateLedgerTransactionParams struct {
	ID            pgtype.UUID `json:"id"`
	Type          string      `json:"type"`
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
	Description   pgtype.Text `json:"description"`
}

func (q *Queries) CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) (LedgerTransactions, error) {
	row := q.db.QueryRow(ctx, createLedgerTransaction,
		arg.ID,
		arg.Type,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Description,
	)
	var i LedgerTransactions
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, transaction_id, account_type, account_id, direction, amount_minor, currency, created_at FROM ledger_entries
WHERE account_type = $1 AND account_id = $2
ORDER BY created_at DESC
`

type ListLedgerEntriesByAccountParams struct {
	AccountType string      `json:"account_type"`
	AccountID   pgtype.UUID `json:"account_id"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntries, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.AccountType, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntries
	for rows.Next() {
		var i LedgerEntries
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountType,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByTransactionID = `-- name: ListLedgerEntriesByTransactionID :many
SELECT id, transaction_id, account_type, account_id, direction, amount_minor, currency, created_at FROM ledger_entries
WHERE transaction_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListLedgerEntriesByTransactionID(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntries, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByTransactionID, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntries
	for rows.Next() {
		var i LedgerEntries
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.AccountType,
			&i.AccountID,
			&i.Direction,
			&i.AmountMinor,
			&i.Currency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerTransactionsByReference = `-- name: ListLedgerTransactionsByReference :many
SELECT id, type, reference_type, reference_id, description, created_at FROM ledger_transactions
WHERE reference_type = $1 AND reference_id = $2
ORDER BY created_at ASC
`

type ListLedgerTransactionsByReferenceParams struct {
	ReferenceType pgtype.Text `json:"reference_type"`
	ReferenceID   pgtype.UUID `json:"reference_id"`
}

func (q *Queries) ListLedgerTransactionsByReference(ctx context.Context, arg ListLedgerTransactionsByReferenceParams) ([]LedgerTransactions, error) {
	rows, err := q.db.Query(ctx, listLedgerTransactionsByReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerTransactions
	for rows.Next() {
		var i LedgerTransactions
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentLedgerTransactions = `-- name: ListRecentLedgerTransactions :many
SELECT id, type, reference_type, reference_id, description, created_at FROM ledger_transactions
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentLedgerTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecentLedgerTransactions(ctx context.Context, arg ListRecentLedgerTransactionsParams) ([]LedgerTransactions, error) {
	rows, err := q.db.Query(ctx, listRecentLedgerTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerTransactions
	for rows.Next() {
		var i LedgerTransactions
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
