// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: node_groups.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNodeGroup = `-- name: CreateNodeGroup :one
INSERT INTO node_groups (
  id, name, region, status, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, now(), now()
)
RETURNING id, name, region, status, created_at, updated_at
`

type CreateNodeGroupParams struct {
	ID     pgtype.UUID `json:"id"`
	Name   string      `json:"name"`
	Region string      `json:"region"`
	Status string      `json:"status"`
}

func (q *Queries) CreateNodeGroup(ctx context.Context, arg CreateNodeGroupParams) (NodeGroups, error) {
	row := q.db.QueryRow(ctx, createNodeGroup,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.Status,
	)
	var i NodeGroups
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeGroupByID = `-- name: GetNodeGroupByID :one
SELECT id, name, region, status, created_at, updated_at FROM node_groups
WHERE id = $1
`

func (q *Queries) GetNodeGroupByID(ctx context.Context, id pgtype.UUID) (NodeGroups, error) {
	row := q.db.QueryRow(ctx, getNodeGroupByID, id)
	var i NodeGroups
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodeGroups = `-- name: ListNodeGroups :many
SELECT id, name, region, status, created_at, updated_at FROM node_groups
ORDER BY name ASC
`

func (q *Queries) ListNodeGroups(ctx context.Context) ([]NodeGroups, error) {
	rows, err := q.db.Query(ctx, listNodeGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NodeGroups
	for rows.Next() {
		var i NodeGroups
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
