// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitNodeReservation = `-- name: CommitNodeReservation :exec
UPDATE nodes
SET cpu_reserved = cpu_reserved - $2,
    memory_reserved_mb = memory_reserved_mb - $3,
    disk_reserved_gb = disk_reserved_gb - $4,
    cpu_allocated = cpu_allocated + $2,
    memory_allocated_mb = memory_allocated_mb + $3,
    disk_allocated_gb = disk_allocated_gb + $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
`

type CommitNodeReservationParams struct {
	ID               pgtype.UUID    `json:"id"`
	CpuReserved      pgtype.Numeric `json:"cpu_reserved"`
	MemoryReservedMb int64          `json:"memory_reserved_mb"`
	DiskReservedGb   int64          `json:"disk_reserved_gb"`
}

func (q *Queries) CommitNodeReservation(ctx context.Context, arg CommitNodeReservationParams) error {
	_, err := q.db.Exec(ctx, commitNodeReservation,
		arg.ID,
		arg.CpuReserved,
		arg.MemoryReservedMb,
		arg.DiskReservedGb,
	)
	return err
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (
  id, provider_id, node_group_id, provider_node_id, name, region, status,
  cpu_total, memory_total_mb, disk_total_gb,
  cpu_allocated, memory_allocated_mb, disk_allocated_gb,
  cpu_reserved, memory_reserved_mb, disk_reserved_gb,
  weight, capabilities, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15, $16,
  $17, $18, now(), now()
)
RETURNING id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at
`

type CreateNodeParams struct {
	ID                pgtype.UUID    `json:"id"`
	ProviderID        pgtype.UUID    `json:"provider_id"`
	NodeGroupID       pgtype.UUID    `json:"node_group_id"`
	ProviderNodeID    pgtype.Text    `json:"provider_node_id"`
	Name              string         `json:"name"`
	Region            string         `json:"region"`
	Status            string         `json:"status"`
	CpuTotal          pgtype.Numeric `json:"cpu_total"`
	MemoryTotalMb     int64          `json:"memory_total_mb"`
	DiskTotalGb       int64          `json:"disk_total_gb"`
	CpuAllocated      pgtype.Numeric `json:"cpu_allocated"`
	MemoryAllocatedMb int64          `json:"memory_allocated_mb"`
	DiskAllocatedGb   int64          `json:"disk_allocated_gb"`
	CpuReserved       pgtype.Numeric `json:"cpu_reserved"`
	MemoryReservedMb  int64          `json:"memory_reserved_mb"`
	DiskReservedGb    int64          `json:"disk_reserved_gb"`
	Weight            int32          `json:"weight"`
	Capabilities      []byte         `json:"capabilities"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Nodes, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.ProviderID,
		arg.NodeGroupID,
		arg.ProviderNodeID,
		arg.Name,
		arg.Region,
		arg.Status,
		arg.CpuTotal,
		arg.MemoryTotalMb,
		arg.DiskTotalGb,
		arg.CpuAllocated,
		arg.MemoryAllocatedMb,
		arg.DiskAllocatedGb,
		arg.CpuReserved,
		arg.MemoryReservedMb,
		arg.DiskReservedGb,
		arg.Weight,
		arg.Capabilities,
	)
	var i Nodes
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotal,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocated,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReserved,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at FROM nodes
WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id pgtype.UUID) (Nodes, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Nodes
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotal,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocated,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReserved,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNodeForUpdate = `-- name: GetNodeForUpdate :one
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at FROM nodes
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetNodeForUpdate(ctx context.Context, id pgtype.UUID) (Nodes, error) {
	row := q.db.QueryRow(ctx, getNodeForUpdate, id)
	var i Nodes
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.NodeGroupID,
		&i.ProviderNodeID,
		&i.Name,
		&i.Region,
		&i.Status,
		&i.CpuTotal,
		&i.MemoryTotalMb,
		&i.DiskTotalGb,
		&i.CpuAllocated,
		&i.MemoryAllocatedMb,
		&i.DiskAllocatedGb,
		&i.CpuReserved,
		&i.MemoryReservedMb,
		&i.DiskReservedGb,
		&i.Weight,
		&i.Capabilities,
		&i.LastSeenAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveNodes = `-- name: ListActiveNodes :many
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at FROM nodes
WHERE status = 'active'
ORDER BY weight DESC, created_at ASC
`

func (q *Queries) ListActiveNodes(ctx context.Context) ([]Nodes, error) {
	rows, err := q.db.Query(ctx, listActiveNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nodes
	for rows.Next() {
		var i Nodes
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.NodeGroupID,
			&i.ProviderNodeID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CpuTotal,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuAllocated,
			&i.MemoryAllocatedMb,
			&i.DiskAllocatedGb,
			&i.CpuReserved,
			&i.MemoryReservedMb,
			&i.DiskReservedGb,
			&i.Weight,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at FROM nodes
ORDER BY created_at ASC
`

func (q *Queries) ListNodes(ctx context.Context) ([]Nodes, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nodes
	for rows.Next() {
		var i Nodes
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.NodeGroupID,
			&i.ProviderNodeID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CpuTotal,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuAllocated,
			&i.MemoryAllocatedMb,
			&i.DiskAllocatedGb,
			&i.CpuReserved,
			&i.MemoryReservedMb,
			&i.DiskReservedGb,
			&i.Weight,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesByNodeGroup = `-- name: ListNodesByNodeGroup :many
SELECT id, provider_id, node_group_id, provider_node_id, name, region, status, cpu_total, memory_total_mb, disk_total_gb, cpu_allocated, memory_allocated_mb, disk_allocated_gb, cpu_reserved, memory_reserved_mb, disk_reserved_gb, weight, capabilities, last_seen_at, version, created_at, updated_at FROM nodes
WHERE node_group_id = $1 AND status = 'active'
ORDER BY weight DESC, created_at ASC
`

func (q *Queries) ListNodesByNodeGroup(ctx context.Context, nodeGroupID pgtype.UUID) ([]Nodes, error) {
	rows, err := q.db.Query(ctx, listNodesByNodeGroup, nodeGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nodes
	for rows.Next() {
		var i Nodes
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.NodeGroupID,
			&i.ProviderNodeID,
			&i.Name,
			&i.Region,
			&i.Status,
			&i.CpuTotal,
			&i.MemoryTotalMb,
			&i.DiskTotalGb,
			&i.CpuAllocated,
			&i.MemoryAllocatedMb,
			&i.DiskAllocatedGb,
			&i.CpuReserved,
			&i.MemoryReservedMb,
			&i.DiskReservedGb,
			&i.Weight,
			&i.Capabilities,
			&i.LastSeenAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNodeHeartbeat = `-- name: UpdateNodeHeartbeat :exec
UPDATE nodes
SET last_seen_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateNodeHeartbeat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateNodeHeartbeat, id)
	return err
}

const updateNodeReservationDelta = `-- name: UpdateNodeReservationDelta :exec
UPDATE nodes
SET cpu_reserved = cpu_reserved + $2,
    memory_reserved_mb = memory_reserved_mb + $3,
    disk_reserved_gb = disk_reserved_gb + $4,
    version = version + 1,
    updated_at = now()
WHERE id = $1
`

type UpdateNodeReservationDeltaParams struct {
	ID               pgtype.UUID    `json:"id"`
	CpuReserved      pgtype.Numeric `json:"cpu_reserved"`
	MemoryReservedMb int64          `json:"memory_reserved_mb"`
	DiskReservedGb   int64          `json:"disk_reserved_gb"`
}

func (q *Queries) UpdateNodeReservationDelta(ctx context.Context, arg UpdateNodeReservationDeltaParams) error {
	_, err := q.db.Exec(ctx, updateNodeReservationDelta,
		arg.ID,
		arg.CpuReserved,
		arg.MemoryReservedMb,
		arg.DiskReservedGb,
	)
	return err
}

const updateNodeStatus = `-- name: UpdateNodeStatus :exec
UPDATE nodes
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateNodeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error {
	_, err := q.db.Exec(ctx, updateNodeStatus, arg.ID, arg.Status)
	return err
}
