// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOperation = `-- name: CompleteOperation :exec
UPDATE operations
SET status = 'succeeded',
    progress = 100,
    phase = 'completed',
    message_key = 'operations.completed',
    finished_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteOperation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, completeOperation, id)
	return err
}

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (
  id, type, resource_type, resource_id, status, phase, progress,
  message_key, provider_id, provider_operation_id, idempotency_key,
  retryable, retry_count, max_retries, trace_id, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7,
  $8, $9, $10, $11,
  $12, $13, $14, $15, now(), now()
)
RETURNING id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at
`

type CreateOperationParams struct {
	ID                  pgtype.UUID `json:"id"`
	Type                string      `json:"type"`
	ResourceType        string      `json:"resource_type"`
	ResourceID          pgtype.UUID `json:"resource_id"`
	Status              string      `json:"status"`
	Phase               pgtype.Text `json:"phase"`
	Progress            int32       `json:"progress"`
	MessageKey          pgtype.Text `json:"message_key"`
	ProviderID          pgtype.UUID `json:"provider_id"`
	ProviderOperationID pgtype.Text `json:"provider_operation_id"`
	IdempotencyKey      string      `json:"idempotency_key"`
	Retryable           bool        `json:"retryable"`
	RetryCount          int32       `json:"retry_count"`
	MaxRetries          int32       `json:"max_retries"`
	TraceID             string      `json:"trace_id"`
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (Operations, error) {
	row := q.db.QueryRow(ctx, createOperation,
		arg.ID,
		arg.Type,
		arg.ResourceType,
		arg.ResourceID,
		arg.Status,
		arg.Phase,
		arg.Progress,
		arg.MessageKey,
		arg.ProviderID,
		arg.ProviderOperationID,
		arg.IdempotencyKey,
		arg.Retryable,
		arg.RetryCount,
		arg.MaxRetries,
		arg.TraceID,
	)
	var i Operations
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOperationStep = `-- name: CreateOperationStep :one
INSERT INTO operation_steps (
  id, operation_id, step_key, step_order, status, progress, attempt, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, now(), now()
)
RETURNING id, operation_id, step_key, step_order, status, progress, attempt, error_code, error_message, started_at, finished_at, created_at, updated_at
`

type CreateOperationStepParams struct {
	ID          pgtype.UUID `json:"id"`
	OperationID pgtype.UUID `json:"operation_id"`
	StepKey     string      `json:"step_key"`
	StepOrder   int32       `json:"step_order"`
	Status      string      `json:"status"`
	Progress    int32       `json:"progress"`
	Attempt     int32       `json:"attempt"`
}

func (q *Queries) CreateOperationStep(ctx context.Context, arg CreateOperationStepParams) (OperationSteps, error) {
	row := q.db.QueryRow(ctx, createOperationStep,
		arg.ID,
		arg.OperationID,
		arg.StepKey,
		arg.StepOrder,
		arg.Status,
		arg.Progress,
		arg.Attempt,
	)
	var i OperationSteps
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.StepKey,
		&i.StepOrder,
		&i.Status,
		&i.Progress,
		&i.Attempt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failOperation = `-- name: FailOperation :exec
UPDATE operations
SET status = 'failed',
    error_code = $2,
    error_message = $3,
    finished_at = now(),
    updated_at = now()
WHERE id = $1
`

type FailOperationParams struct {
	ID           pgtype.UUID `json:"id"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailOperation(ctx context.Context, arg FailOperationParams) error {
	_, err := q.db.Exec(ctx, failOperation, arg.ID, arg.ErrorCode, arg.ErrorMessage)
	return err
}

const getOperationByID = `-- name: GetOperationByID :one
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
WHERE id = $1
`

func (q *Queries) GetOperationByID(ctx context.Context, id pgtype.UUID) (Operations, error) {
	row := q.db.QueryRow(ctx, getOperationByID, id)
	var i Operations
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperationByIdempotencyKey = `-- name: GetOperationByIdempotencyKey :one
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
WHERE idempotency_key = $1
`

func (q *Queries) GetOperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Operations, error) {
	row := q.db.QueryRow(ctx, getOperationByIdempotencyKey, idempotencyKey)
	var i Operations
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ResourceType,
		&i.ResourceID,
		&i.Status,
		&i.Phase,
		&i.Progress,
		&i.MessageKey,
		&i.ProviderID,
		&i.ProviderOperationID,
		&i.IdempotencyKey,
		&i.Retryable,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.TraceID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperationSteps = `-- name: ListOperationSteps :many
SELECT id, operation_id, step_key, step_order, status, progress, attempt, error_code, error_message, started_at, finished_at, created_at, updated_at FROM operation_steps
WHERE operation_id = $1
ORDER BY step_order ASC
`

func (q *Queries) ListOperationSteps(ctx context.Context, operationID pgtype.UUID) ([]OperationSteps, error) {
	rows, err := q.db.Query(ctx, listOperationSteps, operationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperationSteps
	for rows.Next() {
		var i OperationSteps
		if err := rows.Scan(
			&i.ID,
			&i.OperationID,
			&i.StepKey,
			&i.StepOrder,
			&i.Status,
			&i.Progress,
			&i.Attempt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOperationsByResource = `-- name: ListOperationsByResource :many
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
`

type ListOperationsByResourceParams struct {
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
}

func (q *Queries) ListOperationsByResource(ctx context.Context, arg ListOperationsByResourceParams) ([]Operations, error) {
	rows, err := q.db.Query(ctx, listOperationsByResource, arg.ResourceType, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operations
	for rows.Next() {
		var i Operations
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.Phase,
			&i.Progress,
			&i.MessageKey,
			&i.ProviderID,
			&i.ProviderOperationID,
			&i.IdempotencyKey,
			&i.Retryable,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOperations = `-- name: ListPendingOperations :many
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
WHERE status IN ('queued', 'retrying')
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingOperations(ctx context.Context, limit int32) ([]Operations, error) {
	rows, err := q.db.Query(ctx, listPendingOperations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operations
	for rows.Next() {
		var i Operations
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.Phase,
			&i.Progress,
			&i.MessageKey,
			&i.ProviderID,
			&i.ProviderOperationID,
			&i.IdempotencyKey,
			&i.Retryable,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentOperations = `-- name: ListRecentOperations :many
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListRecentOperations(ctx context.Context, limit int32) ([]Operations, error) {
	rows, err := q.db.Query(ctx, listRecentOperations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operations
	for rows.Next() {
		var i Operations
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.Phase,
			&i.Progress,
			&i.MessageKey,
			&i.ProviderID,
			&i.ProviderOperationID,
			&i.IdempotencyKey,
			&i.Retryable,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckOperations = `-- name: ListStuckOperations :many
SELECT id, type, resource_type, resource_id, status, phase, progress, message_key, provider_id, provider_operation_id, idempotency_key, retryable, retry_count, max_retries, error_code, error_message, trace_id, started_at, finished_at, created_at, updated_at FROM operations
WHERE status = 'running' AND updated_at < $1
ORDER BY updated_at ASC
`

func (q *Queries) ListStuckOperations(ctx context.Context, updatedAt pgtype.Timestamptz) ([]Operations, error) {
	rows, err := q.db.Query(ctx, listStuckOperations, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Operations
	for rows.Next() {
		var i Operations
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ResourceType,
			&i.ResourceID,
			&i.Status,
			&i.Phase,
			&i.Progress,
			&i.MessageKey,
			&i.ProviderID,
			&i.ProviderOperationID,
			&i.IdempotencyKey,
			&i.Retryable,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.TraceID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOperationProviderInfo = `-- name: SetOperationProviderInfo :exec
UPDATE operations
SET provider_id = $2,
    provider_operation_id = $3,
    updated_at = now()
WHERE id = $1
`

type SetOperationProviderInfoParams struct {
	ID                  pgtype.UUID `json:"id"`
	ProviderID          pgtype.UUID `json:"provider_id"`
	ProviderOperationID pgtype.Text `json:"provider_operation_id"`
}

func (q *Queries) SetOperationProviderInfo(ctx context.Context, arg SetOperationProviderInfoParams) error {
	_, err := q.db.Exec(ctx, setOperationProviderInfo, arg.ID, arg.ProviderID, arg.ProviderOperationID)
	return err
}

const updateOperationProgress = `-- name: UpdateOperationProgress :exec
UPDATE operations
SET status = $2,
    phase = $3,
    progress = $4,
    message_key = $5,
    started_at = COALESCE(started_at, $6),
    updated_at = now()
WHERE id = $1
`

type UpdateOperationProgressParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	Phase      pgtype.Text        `json:"phase"`
	Progress   int32              `json:"progress"`
	MessageKey pgtype.Text        `json:"message_key"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) UpdateOperationProgress(ctx context.Context, arg UpdateOperationProgressParams) error {
	_, err := q.db.Exec(ctx, updateOperationProgress,
		arg.ID,
		arg.Status,
		arg.Phase,
		arg.Progress,
		arg.MessageKey,
		arg.StartedAt,
	)
	return err
}

const updateOperationStep = `-- name: UpdateOperationStep :exec
UPDATE operation_steps
SET status = $3,
    progress = $4,
    attempt = attempt + 1,
    error_code = $5,
    error_message = $6,
    started_at = COALESCE(started_at, $7),
    finished_at = $8,
    updated_at = now()
WHERE operation_id = $1 AND step_key = $2
`

type UpdateOperationStepParams struct {
	OperationID  pgtype.UUID        `json:"operation_id"`
	StepKey      string             `json:"step_key"`
	Status       string             `json:"status"`
	Progress     int32              `json:"progress"`
	ErrorCode    pgtype.Text        `json:"error_code"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateOperationStep(ctx context.Context, arg UpdateOperationStepParams) error {
	_, err := q.db.Exec(ctx, updateOperationStep,
		arg.OperationID,
		arg.StepKey,
		arg.Status,
		arg.Progress,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}
