// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now(), now()
) RETURNING id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at
`

type CreateOrderParams struct {
	ID            pgtype.UUID `json:"id"`
	OrderNo       string      `json:"order_no"`
	UserID        pgtype.UUID `json:"user_id"`
	Status        string      `json:"status"`
	SubtotalMinor int64       `json:"subtotal_minor"`
	DiscountMinor int64       `json:"discount_minor"`
	TotalMinor    int64       `json:"total_minor"`
	Currency      string      `json:"currency"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.OrderNo,
		arg.UserID,
		arg.Status,
		arg.SubtotalMinor,
		arg.DiscountMinor,
		arg.TotalMinor,
		arg.Currency,
	)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (
    id, order_id, product_id, plan_id, quantity, unit_price_minor, total_minor,
    product_snapshot, plan_snapshot, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, now()
) RETURNING id, order_id, product_id, plan_id, quantity, unit_price_minor, total_minor, product_snapshot, plan_snapshot, created_at
`

type CreateOrderItemParams struct {
	ID              pgtype.UUID `json:"id"`
	OrderID         pgtype.UUID `json:"order_id"`
	ProductID       pgtype.UUID `json:"product_id"`
	PlanID          pgtype.UUID `json:"plan_id"`
	Quantity        int32       `json:"quantity"`
	UnitPriceMinor  int64       `json:"unit_price_minor"`
	TotalMinor      int64       `json:"total_minor"`
	ProductSnapshot []byte      `json:"product_snapshot"`
	PlanSnapshot    []byte      `json:"plan_snapshot"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItems, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.ID,
		arg.OrderID,
		arg.ProductID,
		arg.PlanID,
		arg.Quantity,
		arg.UnitPriceMinor,
		arg.TotalMinor,
		arg.ProductSnapshot,
		arg.PlanSnapshot,
	)
	var i OrderItems
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.PlanID,
		&i.Quantity,
		&i.UnitPriceMinor,
		&i.TotalMinor,
		&i.ProductSnapshot,
		&i.PlanSnapshot,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Orders, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByOrderNo = `-- name: GetOrderByOrderNo :one
SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at FROM orders
WHERE order_no = $1 LIMIT 1
`

func (q *Queries) GetOrderByOrderNo(ctx context.Context, orderNo string) (Orders, error) {
	row := q.db.QueryRow(ctx, getOrderByOrderNo, orderNo)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllOrders = `-- name: ListAllOrders :many
SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at FROM orders
ORDER BY created_at DESC
`

func (q *Queries) ListAllOrders(ctx context.Context) ([]Orders, error) {
	rows, err := q.db.Query(ctx, listAllOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orders
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.Status,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.TotalMinor,
			&i.Currency,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT id, order_id, product_id, plan_id, quantity, unit_price_minor, total_minor, product_snapshot, plan_snapshot, created_at FROM order_items
WHERE order_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItems, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItems
	for rows.Next() {
		var i OrderItems
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.PlanID,
			&i.Quantity,
			&i.UnitPriceMinor,
			&i.TotalMinor,
			&i.ProductSnapshot,
			&i.PlanSnapshot,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserID = `-- name: ListOrdersByUserID :many
SELECT id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Orders, error) {
	rows, err := q.db.Query(ctx, listOrdersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Orders
	for rows.Next() {
		var i Orders
		if err := rows.Scan(
			&i.ID,
			&i.OrderNo,
			&i.UserID,
			&i.Status,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.TotalMinor,
			&i.Currency,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    paid_at = CASE WHEN $2 = 'paid' THEN now() ELSE paid_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, order_no, user_id, status, subtotal_minor, discount_minor, total_minor, currency, paid_at, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Orders, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Orders
	err := row.Scan(
		&i.ID,
		&i.OrderNo,
		&i.UserID,
		&i.Status,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TotalMinor,
		&i.Currency,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
