// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOutboxEvent = `-- name: CreateOutboxEvent :one
INSERT INTO outbox_events (
    id, event_type, aggregate_type, aggregate_id, payload,
    status, attempts, next_attempt_at, created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, now()
) RETURNING id, event_type, aggregate_type, aggregate_id, payload, status, attempts, next_attempt_at, created_at, published_at
`

type CreateOutboxEventParams struct {
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	Payload       []byte             `json:"payload"`
	Status        string             `json:"status"`
	Attempts      int32              `json:"attempts"`
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
}

func (q *Queries) CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvents, error) {
	row := q.db.QueryRow(ctx, createOutboxEvent,
		arg.ID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
	)
	var i OutboxEvents
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}

const listOutboxEventsByAggregate = `-- name: ListOutboxEventsByAggregate :many
SELECT id, event_type, aggregate_type, aggregate_id, payload, status, attempts, next_attempt_at, created_at, published_at FROM outbox_events
WHERE aggregate_type = $1 AND aggregate_id = $2
ORDER BY created_at ASC
`

type ListOutboxEventsByAggregateParams struct {
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
}

func (q *Queries) ListOutboxEventsByAggregate(ctx context.Context, arg ListOutboxEventsByAggregateParams) ([]OutboxEvents, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsByAggregate, arg.AggregateType, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvents
	for rows.Next() {
		var i OutboxEvents
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, event_type, aggregate_type, aggregate_id, payload, status, attempts, next_attempt_at, created_at, published_at FROM outbox_events
WHERE status = 'pending' AND next_attempt_at <= now()
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvents, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxEvents
	for rows.Next() {
		var i OutboxEvents
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :one
UPDATE outbox_events
SET status = 'published',
    published_at = now()
WHERE id = $1
RETURNING id, event_type, aggregate_type, aggregate_id, payload, status, attempts, next_attempt_at, created_at, published_at
`

func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) (OutboxEvents, error) {
	row := q.db.QueryRow(ctx, markOutboxEventPublished, id)
	var i OutboxEvents
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.PublishedAt,
	)
	return i, err
}
