// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    id, payment_no, order_id, gateway, gateway_payment_id, status,
    amount_minor, currency, idempotency_key, gateway_payload, paid_at,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    now(), now()
) RETURNING id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	ID               pgtype.UUID        `json:"id"`
	PaymentNo        string             `json:"payment_no"`
	OrderID          pgtype.UUID        `json:"order_id"`
	Gateway          string             `json:"gateway"`
	GatewayPaymentID pgtype.Text        `json:"gateway_payment_id"`
	Status           string             `json:"status"`
	AmountMinor      int64              `json:"amount_minor"`
	Currency         string             `json:"currency"`
	IdempotencyKey   string             `json:"idempotency_key"`
	GatewayPayload   []byte             `json:"gateway_payload"`
	PaidAt           pgtype.Timestamptz `json:"paid_at"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payments, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ID,
		arg.PaymentNo,
		arg.OrderID,
		arg.Gateway,
		arg.GatewayPaymentID,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.IdempotencyKey,
		arg.GatewayPayload,
		arg.PaidAt,
	)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByGatewayAndExternalID = `-- name: GetPaymentByGatewayAndExternalID :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE gateway = $1 AND gateway_payment_id = $2 LIMIT 1
`

type GetPaymentByGatewayAndExternalIDParams struct {
	Gateway          string      `json:"gateway"`
	GatewayPaymentID pgtype.Text `json:"gateway_payment_id"`
}

func (q *Queries) GetPaymentByGatewayAndExternalID(ctx context.Context, arg GetPaymentByGatewayAndExternalIDParams) (Payments, error) {
	row := q.db.QueryRow(ctx, getPaymentByGatewayAndExternalID, arg.Gateway, arg.GatewayPaymentID)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByGatewayAndExternalIDForUpdate = `-- name: GetPaymentByGatewayAndExternalIDForUpdate :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE gateway = $1 AND gateway_payment_id = $2 LIMIT 1 FOR UPDATE
`

type GetPaymentByGatewayAndExternalIDForUpdateParams struct {
	Gateway          string      `json:"gateway"`
	GatewayPaymentID pgtype.Text `json:"gateway_payment_id"`
}

func (q *Queries) GetPaymentByGatewayAndExternalIDForUpdate(ctx context.Context, arg GetPaymentByGatewayAndExternalIDForUpdateParams) (Payments, error) {
	row := q.db.QueryRow(ctx, getPaymentByGatewayAndExternalIDForUpdate, arg.Gateway, arg.GatewayPaymentID)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payments, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKey = `-- name: GetPaymentByIdempotencyKey :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payments, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKey, idempotencyKey)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByIdempotencyKeyForUpdate = `-- name: GetPaymentByIdempotencyKeyForUpdate :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE idempotency_key = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetPaymentByIdempotencyKeyForUpdate(ctx context.Context, idempotencyKey string) (Payments, error) {
	row := q.db.QueryRow(ctx, getPaymentByIdempotencyKeyForUpdate, idempotencyKey)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByPaymentNo = `-- name: GetPaymentByPaymentNo :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE payment_no = $1 LIMIT 1
`

func (q *Queries) GetPaymentByPaymentNo(ctx context.Context, paymentNo string) (Payments, error) {
	row := q.db.QueryRow(ctx, getPaymentByPaymentNo, paymentNo)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentForUpdate = `-- name: GetPaymentForUpdate :one
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetPaymentForUpdate(ctx context.Context, id pgtype.UUID) (Payments, error) {
	row := q.db.QueryRow(ctx, getPaymentForUpdate, id)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllPayments = `-- name: ListAllPayments :many
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
ORDER BY created_at DESC
`

func (q *Queries) ListAllPayments(ctx context.Context) ([]Payments, error) {
	rows, err := q.db.Query(ctx, listAllPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payments
	for rows.Next() {
		var i Payments
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNo,
			&i.OrderID,
			&i.Gateway,
			&i.GatewayPaymentID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.IdempotencyKey,
			&i.GatewayPayload,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByOrderID = `-- name: ListPaymentsByOrderID :many
SELECT id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at FROM payments
WHERE order_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPaymentsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Payments, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payments
	for rows.Next() {
		var i Payments
		if err := rows.Scan(
			&i.ID,
			&i.PaymentNo,
			&i.OrderID,
			&i.Gateway,
			&i.GatewayPaymentID,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.IdempotencyKey,
			&i.GatewayPayload,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2,
    gateway_payment_id = COALESCE($3, gateway_payment_id),
    gateway_payload = COALESCE($4, gateway_payload),
    paid_at = CASE WHEN $2 = 'succeeded' THEN now() ELSE paid_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, payment_no, order_id, gateway, gateway_payment_id, status, amount_minor, currency, idempotency_key, gateway_payload, paid_at, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID               pgtype.UUID `json:"id"`
	Status           string      `json:"status"`
	GatewayPaymentID pgtype.Text `json:"gateway_payment_id"`
	GatewayPayload   []byte      `json:"gateway_payload"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payments, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus,
		arg.ID,
		arg.Status,
		arg.GatewayPaymentID,
		arg.GatewayPayload,
	)
	var i Payments
	err := row.Scan(
		&i.ID,
		&i.PaymentNo,
		&i.OrderID,
		&i.Gateway,
		&i.GatewayPaymentID,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.IdempotencyKey,
		&i.GatewayPayload,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
