// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans (
    id, product_id, node_group_id, slug, name_i18n, status,
    cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps,
    ipv4_count, ipv6_count, nat_port_count, virtualization,
    billing_cycle, price_minor, currency, stock_mode,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18, $19,
    now(), now()
) RETURNING id, product_id, node_group_id, slug, name_i18n, status, cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle, price_minor, currency, stock_mode, created_at, updated_at
`

type CreatePlanParams struct {
	ID             pgtype.UUID    `json:"id"`
	ProductID      pgtype.UUID    `json:"product_id"`
	NodeGroupID    pgtype.UUID    `json:"node_group_id"`
	Slug           string         `json:"slug"`
	NameI18n       []byte         `json:"name_i18n"`
	Status         string         `json:"status"`
	CpuCores       pgtype.Numeric `json:"cpu_cores"`
	MemoryMb       int32          `json:"memory_mb"`
	DiskGb         int32          `json:"disk_gb"`
	TrafficGb      pgtype.Int8    `json:"traffic_gb"`
	BandwidthMbps  pgtype.Int4    `json:"bandwidth_mbps"`
	Ipv4Count      int32          `json:"ipv4_count"`
	Ipv6Count      int32          `json:"ipv6_count"`
	NatPortCount   int32          `json:"nat_port_count"`
	Virtualization string         `json:"virtualization"`
	BillingCycle   string         `json:"billing_cycle"`
	PriceMinor     int64          `json:"price_minor"`
	Currency       string         `json:"currency"`
	StockMode      string         `json:"stock_mode"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plans, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.ID,
		arg.ProductID,
		arg.NodeGroupID,
		arg.Slug,
		arg.NameI18n,
		arg.Status,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.TrafficGb,
		arg.BandwidthMbps,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
		arg.Virtualization,
		arg.BillingCycle,
		arg.PriceMinor,
		arg.Currency,
		arg.StockMode,
	)
	var i Plans
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.NodeGroupID,
		&i.Slug,
		&i.NameI18n,
		&i.Status,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StockMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByID = `-- name: GetPlanByID :one
SELECT id, product_id, node_group_id, slug, name_i18n, status, cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle, price_minor, currency, stock_mode, created_at, updated_at FROM plans
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlanByID(ctx context.Context, id pgtype.UUID) (Plans, error) {
	row := q.db.QueryRow(ctx, getPlanByID, id)
	var i Plans
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.NodeGroupID,
		&i.Slug,
		&i.NameI18n,
		&i.Status,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StockMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByProductAndSlug = `-- name: GetPlanByProductAndSlug :one
SELECT id, product_id, node_group_id, slug, name_i18n, status, cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle, price_minor, currency, stock_mode, created_at, updated_at FROM plans
WHERE product_id = $1 AND slug = $2 LIMIT 1
`

type GetPlanByProductAndSlugParams struct {
	ProductID pgtype.UUID `json:"product_id"`
	Slug      string      `json:"slug"`
}

func (q *Queries) GetPlanByProductAndSlug(ctx context.Context, arg GetPlanByProductAndSlugParams) (Plans, error) {
	row := q.db.QueryRow(ctx, getPlanByProductAndSlug, arg.ProductID, arg.Slug)
	var i Plans
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.NodeGroupID,
		&i.Slug,
		&i.NameI18n,
		&i.Status,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StockMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePlansByProductID = `-- name: ListActivePlansByProductID :many
SELECT id, product_id, node_group_id, slug, name_i18n, status, cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle, price_minor, currency, stock_mode, created_at, updated_at FROM plans
WHERE product_id = $1 AND status = 'active'
ORDER BY price_minor ASC, created_at ASC
`

func (q *Queries) ListActivePlansByProductID(ctx context.Context, productID pgtype.UUID) ([]Plans, error) {
	rows, err := q.db.Query(ctx, listActivePlansByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plans
	for rows.Next() {
		var i Plans
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.NodeGroupID,
			&i.Slug,
			&i.NameI18n,
			&i.Status,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficGb,
			&i.BandwidthMbps,
			&i.Ipv4Count,
			&i.Ipv6Count,
			&i.NatPortCount,
			&i.Virtualization,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StockMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActivePlans = `-- name: ListAllActivePlans :many
SELECT id, product_id, node_group_id, slug, name_i18n, status, cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle, price_minor, currency, stock_mode, created_at, updated_at FROM plans
WHERE status = 'active'
ORDER BY price_minor ASC, created_at ASC
`

func (q *Queries) ListAllActivePlans(ctx context.Context) ([]Plans, error) {
	rows, err := q.db.Query(ctx, listAllActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plans
	for rows.Next() {
		var i Plans
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.NodeGroupID,
			&i.Slug,
			&i.NameI18n,
			&i.Status,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficGb,
			&i.BandwidthMbps,
			&i.Ipv4Count,
			&i.Ipv6Count,
			&i.NatPortCount,
			&i.Virtualization,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StockMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlansByProductID = `-- name: ListPlansByProductID :many
SELECT id, product_id, node_group_id, slug, name_i18n, status, cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle, price_minor, currency, stock_mode, created_at, updated_at FROM plans
WHERE product_id = $1
ORDER BY price_minor ASC, created_at ASC
`

func (q *Queries) ListPlansByProductID(ctx context.Context, productID pgtype.UUID) ([]Plans, error) {
	rows, err := q.db.Query(ctx, listPlansByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plans
	for rows.Next() {
		var i Plans
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.NodeGroupID,
			&i.Slug,
			&i.NameI18n,
			&i.Status,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.TrafficGb,
			&i.BandwidthMbps,
			&i.Ipv4Count,
			&i.Ipv6Count,
			&i.NatPortCount,
			&i.Virtualization,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StockMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET name_i18n = $2,
    status = $3,
    cpu_cores = $4,
    memory_mb = $5,
    disk_gb = $6,
    traffic_gb = $7,
    bandwidth_mbps = $8,
    ipv4_count = $9,
    ipv6_count = $10,
    nat_port_count = $11,
    price_minor = $12,
    currency = $13,
    stock_mode = $14,
    updated_at = now()
WHERE id = $1
RETURNING id, product_id, node_group_id, slug, name_i18n, status, cpu_cores, memory_mb, disk_gb, traffic_gb, bandwidth_mbps, ipv4_count, ipv6_count, nat_port_count, virtualization, billing_cycle, price_minor, currency, stock_mode, created_at, updated_at
`

type UpdatePlanParams struct {
	ID            pgtype.UUID    `json:"id"`
	NameI18n      []byte         `json:"name_i18n"`
	Status        string         `json:"status"`
	CpuCores      pgtype.Numeric `json:"cpu_cores"`
	MemoryMb      int32          `json:"memory_mb"`
	DiskGb        int32          `json:"disk_gb"`
	TrafficGb     pgtype.Int8    `json:"traffic_gb"`
	BandwidthMbps pgtype.Int4    `json:"bandwidth_mbps"`
	Ipv4Count     int32          `json:"ipv4_count"`
	Ipv6Count     int32          `json:"ipv6_count"`
	NatPortCount  int32          `json:"nat_port_count"`
	PriceMinor    int64          `json:"price_minor"`
	Currency      string         `json:"currency"`
	StockMode     string         `json:"stock_mode"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plans, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.ID,
		arg.NameI18n,
		arg.Status,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.TrafficGb,
		arg.BandwidthMbps,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
		arg.PriceMinor,
		arg.Currency,
		arg.StockMode,
	)
	var i Plans
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.NodeGroupID,
		&i.Slug,
		&i.NameI18n,
		&i.Status,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.TrafficGb,
		&i.BandwidthMbps,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Virtualization,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StockMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
