// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, now(), now()
) RETURNING id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at
`

type CreateProductParams struct {
	ID              pgtype.UUID `json:"id"`
	Slug            string      `json:"slug"`
	NameI18n        []byte      `json:"name_i18n"`
	DescriptionI18n []byte      `json:"description_i18n"`
	Status          string      `json:"status"`
	SortOrder       int32       `json:"sort_order"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Products, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.Slug,
		arg.NameI18n,
		arg.DescriptionI18n,
		arg.Status,
		arg.SortOrder,
	)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Products, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at FROM products
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (Products, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveProducts = `-- name: ListActiveProducts :many
SELECT id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at FROM products
WHERE status = 'active'
ORDER BY sort_order ASC, created_at DESC
`

func (q *Queries) ListActiveProducts(ctx context.Context) ([]Products, error) {
	rows, err := q.db.Query(ctx, listActiveProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Products
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at FROM products
ORDER BY sort_order ASC, created_at DESC
`

func (q *Queries) ListProducts(ctx context.Context) ([]Products, error) {
	rows, err := q.db.Query(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Products
	for rows.Next() {
		var i Products
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.NameI18n,
			&i.DescriptionI18n,
			&i.Status,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name_i18n = $2,
    description_i18n = $3,
    status = $4,
    sort_order = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, slug, name_i18n, description_i18n, status, sort_order, created_at, updated_at
`

type UpdateProductParams struct {
	ID              pgtype.UUID `json:"id"`
	NameI18n        []byte      `json:"name_i18n"`
	DescriptionI18n []byte      `json:"description_i18n"`
	Status          string      `json:"status"`
	SortOrder       int32       `json:"sort_order"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Products, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.NameI18n,
		arg.DescriptionI18n,
		arg.Status,
		arg.SortOrder,
	)
	var i Products
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.NameI18n,
		&i.DescriptionI18n,
		&i.Status,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
