// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (
  id, name, provider_type, endpoint, credential_ref, status, version, config, capabilities, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now()
)
RETURNING id, name, provider_type, endpoint, credential_ref, status, version, config, capabilities, last_health_check_at, created_at, updated_at
`

type CreateProviderParams struct {
	ID            pgtype.UUID `json:"id"`
	Name          string      `json:"name"`
	ProviderType  string      `json:"provider_type"`
	Endpoint      pgtype.Text `json:"endpoint"`
	CredentialRef pgtype.Text `json:"credential_ref"`
	Status        string      `json:"status"`
	Version       pgtype.Text `json:"version"`
	Config        []byte      `json:"config"`
	Capabilities  []byte      `json:"capabilities"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Providers, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.ID,
		arg.Name,
		arg.ProviderType,
		arg.Endpoint,
		arg.CredentialRef,
		arg.Status,
		arg.Version,
		arg.Config,
		arg.Capabilities,
	)
	var i Providers
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Endpoint,
		&i.CredentialRef,
		&i.Status,
		&i.Version,
		&i.Config,
		&i.Capabilities,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, provider_type, endpoint, credential_ref, status, version, config, capabilities, last_health_check_at, created_at, updated_at FROM providers
WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id pgtype.UUID) (Providers, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Providers
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Endpoint,
		&i.CredentialRef,
		&i.Status,
		&i.Version,
		&i.Config,
		&i.Capabilities,
		&i.LastHealthCheckAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, provider_type, endpoint, credential_ref, status, version, config, capabilities, last_health_check_at, created_at, updated_at FROM providers
ORDER BY created_at ASC
`

func (q *Queries) ListProviders(ctx context.Context) ([]Providers, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Providers
	for rows.Next() {
		var i Providers
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Endpoint,
			&i.CredentialRef,
			&i.Status,
			&i.Version,
			&i.Config,
			&i.Capabilities,
			&i.LastHealthCheckAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProviderHealth = `-- name: UpdateProviderHealth :exec
UPDATE providers
SET status = $2, last_health_check_at = now(), updated_at = now()
WHERE id = $1
`

type UpdateProviderHealthParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateProviderHealth(ctx context.Context, arg UpdateProviderHealthParams) error {
	_, err := q.db.Exec(ctx, updateProviderHealth, arg.ID, arg.Status)
	return err
}
