// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToAdmin(ctx context.Context, arg AssignRoleToAdminParams) error
	CommitNodeReservation(ctx context.Context, arg CommitNodeReservationParams) error
	CompleteOperation(ctx context.Context, id pgtype.UUID) error
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admins, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) (AuditEvents, error)
	CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instances, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoices, error)
	CreateInvoiceItem(ctx context.Context, arg CreateInvoiceItemParams) (InvoiceItems, error)
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntries, error)
	CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) (LedgerTransactions, error)
	CreateNode(ctx context.Context, arg CreateNodeParams) (Nodes, error)
	CreateNodeGroup(ctx context.Context, arg CreateNodeGroupParams) (NodeGroups, error)
	CreateOperation(ctx context.Context, arg CreateOperationParams) (Operations, error)
	CreateOperationStep(ctx context.Context, arg CreateOperationStepParams) (OperationSteps, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Orders, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItems, error)
	CreateOutboxEvent(ctx context.Context, arg CreateOutboxEventParams) (OutboxEvents, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payments, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permissions, error)
	CreatePlan(ctx context.Context, arg CreatePlanParams) (Plans, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Products, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Providers, error)
	CreateResourceReservation(ctx context.Context, arg CreateResourceReservationParams) (ResourceReservations, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Roles, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscriptions, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallets, error)
	FailOperation(ctx context.Context, arg FailOperationParams) error
	GetAdminByEmail(ctx context.Context, email string) (Admins, error)
	GetAdminByID(ctx context.Context, id pgtype.UUID) (Admins, error)
	GetAdminPermissions(ctx context.Context, adminID pgtype.UUID) ([]string, error)
	GetAdminRoles(ctx context.Context, adminID pgtype.UUID) ([]Roles, error)
	GetInstanceByID(ctx context.Context, id pgtype.UUID) (Instances, error)
	GetInstanceBySubscriptionID(ctx context.Context, subscriptionID pgtype.UUID) (Instances, error)
	GetInvoiceByID(ctx context.Context, id pgtype.UUID) (Invoices, error)
	GetInvoiceByInvoiceNo(ctx context.Context, invoiceNo string) (Invoices, error)
	GetInvoiceByOrderID(ctx context.Context, orderID pgtype.UUID) (Invoices, error)
	GetNodeByID(ctx context.Context, id pgtype.UUID) (Nodes, error)
	GetNodeForUpdate(ctx context.Context, id pgtype.UUID) (Nodes, error)
	GetNodeGroupByID(ctx context.Context, id pgtype.UUID) (NodeGroups, error)
	GetOperationByID(ctx context.Context, id pgtype.UUID) (Operations, error)
	GetOperationByIdempotencyKey(ctx context.Context, idempotencyKey string) (Operations, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Orders, error)
	GetOrderByOrderNo(ctx context.Context, orderNo string) (Orders, error)
	GetPaymentByGatewayAndExternalID(ctx context.Context, arg GetPaymentByGatewayAndExternalIDParams) (Payments, error)
	GetPaymentByGatewayAndExternalIDForUpdate(ctx context.Context, arg GetPaymentByGatewayAndExternalIDForUpdateParams) (Payments, error)
	GetPaymentByID(ctx context.Context, id pgtype.UUID) (Payments, error)
	GetPaymentByIdempotencyKey(ctx context.Context, idempotencyKey string) (Payments, error)
	GetPaymentByIdempotencyKeyForUpdate(ctx context.Context, idempotencyKey string) (Payments, error)
	GetPaymentByPaymentNo(ctx context.Context, paymentNo string) (Payments, error)
	GetPaymentForUpdate(ctx context.Context, id pgtype.UUID) (Payments, error)
	GetPlanByID(ctx context.Context, id pgtype.UUID) (Plans, error)
	GetPlanByProductAndSlug(ctx context.Context, arg GetPlanByProductAndSlugParams) (Plans, error)
	GetProductByID(ctx context.Context, id pgtype.UUID) (Products, error)
	GetProductBySlug(ctx context.Context, slug string) (Products, error)
	GetProviderByID(ctx context.Context, id pgtype.UUID) (Providers, error)
	GetResourceReservationByID(ctx context.Context, id pgtype.UUID) (ResourceReservations, error)
	GetResourceReservationByOperationID(ctx context.Context, operationID pgtype.UUID) (ResourceReservations, error)
	GetRoleByKey(ctx context.Context, key string) (Roles, error)
	GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (Subscriptions, error)
	GetSubscriptionForUpdate(ctx context.Context, id pgtype.UUID) (Subscriptions, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error)
	GetWalletByUserID(ctx context.Context, arg GetWalletByUserIDParams) (Wallets, error)
	GetWalletByUserIDForUpdate(ctx context.Context, arg GetWalletByUserIDForUpdateParams) (Wallets, error)
	ListActiveNodes(ctx context.Context) ([]Nodes, error)
	ListActivePlansByProductID(ctx context.Context, productID pgtype.UUID) ([]Plans, error)
	ListActiveProducts(ctx context.Context) ([]Products, error)
	ListAdmins(ctx context.Context) ([]Admins, error)
	ListAllActivePlans(ctx context.Context) ([]Plans, error)
	ListAllInvoices(ctx context.Context) ([]Invoices, error)
	ListAllOrders(ctx context.Context) ([]Orders, error)
	ListAllPayments(ctx context.Context) ([]Payments, error)
	ListAllSubscriptions(ctx context.Context) ([]Subscriptions, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvents, error)
	ListDueSubscriptions(ctx context.Context, arg ListDueSubscriptionsParams) ([]Subscriptions, error)
	ListExpiredReservations(ctx context.Context) ([]ResourceReservations, error)
	ListGraceExpiredSubscriptions(ctx context.Context, arg ListGraceExpiredSubscriptionsParams) ([]Subscriptions, error)
	ListInstances(ctx context.Context) ([]Instances, error)
	ListInstancesByNodeID(ctx context.Context, nodeID pgtype.UUID) ([]Instances, error)
	ListInvoiceItemsByInvoiceID(ctx context.Context, invoiceID pgtype.UUID) ([]InvoiceItems, error)
	ListInvoicesByUserID(ctx context.Context, userID pgtype.UUID) ([]Invoices, error)
	ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntries, error)
	ListLedgerEntriesByTransactionID(ctx context.Context, transactionID pgtype.UUID) ([]LedgerEntries, error)
	ListLedgerTransactionsByReference(ctx context.Context, arg ListLedgerTransactionsByReferenceParams) ([]LedgerTransactions, error)
	ListNodeGroups(ctx context.Context) ([]NodeGroups, error)
	ListNodes(ctx context.Context) ([]Nodes, error)
	ListNodesByNodeGroup(ctx context.Context, nodeGroupID pgtype.UUID) ([]Nodes, error)
	ListOperationSteps(ctx context.Context, operationID pgtype.UUID) ([]OperationSteps, error)
	ListOperationsByResource(ctx context.Context, arg ListOperationsByResourceParams) ([]Operations, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]OrderItems, error)
	ListOrdersByUserID(ctx context.Context, userID pgtype.UUID) ([]Orders, error)
	ListOutboxEventsByAggregate(ctx context.Context, arg ListOutboxEventsByAggregateParams) ([]OutboxEvents, error)
	ListPaymentsByOrderID(ctx context.Context, orderID pgtype.UUID) ([]Payments, error)
	ListPendingOperations(ctx context.Context, limit int32) ([]Operations, error)
	ListPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvents, error)
	ListPlansByProductID(ctx context.Context, productID pgtype.UUID) ([]Plans, error)
	ListProducts(ctx context.Context) ([]Products, error)
	ListProviders(ctx context.Context) ([]Providers, error)
	ListRecentLedgerTransactions(ctx context.Context, arg ListRecentLedgerTransactionsParams) ([]LedgerTransactions, error)
	ListRecentOperations(ctx context.Context, limit int32) ([]Operations, error)
	ListStuckOperations(ctx context.Context, updatedAt pgtype.Timestamptz) ([]Operations, error)
	ListSubscriptionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Subscriptions, error)
	ListUsers(ctx context.Context, limit int32) ([]Users, error)
	MarkOutboxEventPublished(ctx context.Context, id pgtype.UUID) (OutboxEvents, error)
	RenewSubscription(ctx context.Context, arg RenewSubscriptionParams) (Subscriptions, error)
	SetCancelAtPeriodEnd(ctx context.Context, arg SetCancelAtPeriodEndParams) (Subscriptions, error)
	SetOperationProviderInfo(ctx context.Context, arg SetOperationProviderInfoParams) error
	SoftDeleteInstance(ctx context.Context, id pgtype.UUID) error
	UpdateAdminLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateAdminStatus(ctx context.Context, arg UpdateAdminStatusParams) (Admins, error)
	UpdateAdminTwoFactor(ctx context.Context, arg UpdateAdminTwoFactorParams) error
	UpdateInstanceStates(ctx context.Context, arg UpdateInstanceStatesParams) error
	UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoices, error)
	UpdateNodeHeartbeat(ctx context.Context, id pgtype.UUID) error
	UpdateNodeReservationDelta(ctx context.Context, arg UpdateNodeReservationDeltaParams) error
	UpdateNodeStatus(ctx context.Context, arg UpdateNodeStatusParams) error
	UpdateOperationProgress(ctx context.Context, arg UpdateOperationProgressParams) error
	UpdateOperationStep(ctx context.Context, arg UpdateOperationStepParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Orders, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payments, error)
	UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plans, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Products, error)
	UpdateProviderHealth(ctx context.Context, arg UpdateProviderHealthParams) error
	UpdateResourceReservationStatus(ctx context.Context, arg UpdateResourceReservationStatusParams) error
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscriptions, error)
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (Users, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (Users, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallets, error)
}

var _ Querier = (*Queries)(nil)
