// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec
INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToAdmin = `-- name: AssignRoleToAdmin :exec
INSERT INTO admin_roles (admin_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToAdminParams struct {
	AdminID pgtype.UUID `json:"admin_id"`
	RoleID  pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToAdmin(ctx context.Context, arg AssignRoleToAdminParams) error {
	_, err := q.db.Exec(ctx, assignRoleToAdmin, arg.AdminID, arg.RoleID)
	return err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (id, key)
VALUES ($1, $2)
ON CONFLICT (key) DO NOTHING
RETURNING id, key
`

type CreatePermissionParams struct {
	ID  pgtype.UUID `json:"id"`
	Key string      `json:"key"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permissions, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.ID, arg.Key)
	var i Permissions
	err := row.Scan(&i.ID, &i.Key)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (id, key, name_key, created_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE SET name_key = EXCLUDED.name_key
RETURNING id, key, name_key, created_at
`

type CreateRoleParams struct {
	ID      pgtype.UUID `json:"id"`
	Key     string      `json:"key"`
	NameKey string      `json:"name_key"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Roles, error) {
	row := q.db.QueryRow(ctx, createRole, arg.ID, arg.Key, arg.NameKey)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NameKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminPermissions = `-- name: GetAdminPermissions :many
SELECT DISTINCT p.key FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN admin_roles ar ON ar.role_id = rp.role_id
WHERE ar.admin_id = $1
`

func (q *Queries) GetAdminPermissions(ctx context.Context, adminID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getAdminPermissions, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminRoles = `-- name: GetAdminRoles :many
SELECT r.id, r.key, r.name_key, r.created_at FROM roles r
JOIN admin_roles ar ON ar.role_id = r.id
WHERE ar.admin_id = $1
`

func (q *Queries) GetAdminRoles(ctx context.Context, adminID pgtype.UUID) ([]Roles, error) {
	rows, err := q.db.Query(ctx, getAdminRoles, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Roles
	for rows.Next() {
		var i Roles
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.NameKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByKey = `-- name: GetRoleByKey :one
SELECT id, key, name_key, created_at FROM roles
WHERE key = $1 LIMIT 1
`

func (q *Queries) GetRoleByKey(ctx context.Context, key string) (Roles, error) {
	row := q.db.QueryRow(ctx, getRoleByKey, key)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.NameKey,
		&i.CreatedAt,
	)
	return i, err
}
