// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource_reservations.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResourceReservation = `-- name: CreateResourceReservation :one
INSERT INTO resource_reservations (
  id, node_id, operation_id, cpu_cores, memory_mb, disk_gb,
  ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now()
)
RETURNING id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at
`

type CreateResourceReservationParams struct {
	ID           pgtype.UUID        `json:"id"`
	NodeID       pgtype.UUID        `json:"node_id"`
	OperationID  pgtype.UUID        `json:"operation_id"`
	CpuCores     pgtype.Numeric     `json:"cpu_cores"`
	MemoryMb     int64              `json:"memory_mb"`
	DiskGb       int64              `json:"disk_gb"`
	Ipv4Count    int32              `json:"ipv4_count"`
	Ipv6Count    int32              `json:"ipv6_count"`
	NatPortCount int32              `json:"nat_port_count"`
	Status       string             `json:"status"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateResourceReservation(ctx context.Context, arg CreateResourceReservationParams) (ResourceReservations, error) {
	row := q.db.QueryRow(ctx, createResourceReservation,
		arg.ID,
		arg.NodeID,
		arg.OperationID,
		arg.CpuCores,
		arg.MemoryMb,
		arg.DiskGb,
		arg.Ipv4Count,
		arg.Ipv6Count,
		arg.NatPortCount,
		arg.Status,
		arg.ExpiresAt,
	)
	var i ResourceReservations
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OperationID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceReservationByID = `-- name: GetResourceReservationByID :one
SELECT id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at FROM resource_reservations
WHERE id = $1
`

func (q *Queries) GetResourceReservationByID(ctx context.Context, id pgtype.UUID) (ResourceReservations, error) {
	row := q.db.QueryRow(ctx, getResourceReservationByID, id)
	var i ResourceReservations
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OperationID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceReservationByOperationID = `-- name: GetResourceReservationByOperationID :one
SELECT id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at FROM resource_reservations
WHERE operation_id = $1
`

func (q *Queries) GetResourceReservationByOperationID(ctx context.Context, operationID pgtype.UUID) (ResourceReservations, error) {
	row := q.db.QueryRow(ctx, getResourceReservationByOperationID, operationID)
	var i ResourceReservations
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.OperationID,
		&i.CpuCores,
		&i.MemoryMb,
		&i.DiskGb,
		&i.Ipv4Count,
		&i.Ipv6Count,
		&i.NatPortCount,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredReservations = `-- name: ListExpiredReservations :many
SELECT id, node_id, operation_id, cpu_cores, memory_mb, disk_gb, ipv4_count, ipv6_count, nat_port_count, status, expires_at, created_at, updated_at FROM resource_reservations
WHERE status = 'reserved' AND expires_at < now()
`

func (q *Queries) ListExpiredReservations(ctx context.Context) ([]ResourceReservations, error) {
	rows, err := q.db.Query(ctx, listExpiredReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ResourceReservations
	for rows.Next() {
		var i ResourceReservations
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.OperationID,
			&i.CpuCores,
			&i.MemoryMb,
			&i.DiskGb,
			&i.Ipv4Count,
			&i.Ipv6Count,
			&i.NatPortCount,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResourceReservationStatus = `-- name: UpdateResourceReservationStatus :exec
UPDATE resource_reservations
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateResourceReservationStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateResourceReservationStatus(ctx context.Context, arg UpdateResourceReservationStatusParams) error {
	_, err := q.db.Exec(ctx, updateResourceReservationStatus, arg.ID, arg.Status)
	return err
}
