// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    id, user_id, plan_id, status, billing_cycle, price_minor, currency,
    started_at, current_period_start, current_period_end, next_due_at, grace_until,
    cancel_at_period_end, ended_at, version, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12,
    $13, $14, 1, now(), now()
) RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
`

type CreateSubscriptionParams struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	PlanID             pgtype.UUID        `json:"plan_id"`
	Status             string             `json:"status"`
	BillingCycle       string             `json:"billing_cycle"`
	PriceMinor         int64              `json:"price_minor"`
	Currency           string             `json:"currency"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
	GraceUntil         pgtype.Timestamptz `json:"grace_until"`
	CancelAtPeriodEnd  bool               `json:"cancel_at_period_end"`
	EndedAt            pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscriptions, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.PlanID,
		arg.Status,
		arg.BillingCycle,
		arg.PriceMinor,
		arg.Currency,
		arg.StartedAt,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextDueAt,
		arg.GraceUntil,
		arg.CancelAtPeriodEnd,
		arg.EndedAt,
	)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (Subscriptions, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionForUpdate = `-- name: GetSubscriptionForUpdate :one
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE id = $1 LIMIT 1 FOR UPDATE
`

func (q *Queries) GetSubscriptionForUpdate(ctx context.Context, id pgtype.UUID) (Subscriptions, error) {
	row := q.db.QueryRow(ctx, getSubscriptionForUpdate, id)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllSubscriptions = `-- name: ListAllSubscriptions :many
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
ORDER BY created_at DESC
`

func (q *Queries) ListAllSubscriptions(ctx context.Context) ([]Subscriptions, error) {
	rows, err := q.db.Query(ctx, listAllSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriptions
	for rows.Next() {
		var i Subscriptions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSubscriptions = `-- name: ListDueSubscriptions :many
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE status = 'active' AND next_due_at <= $1
ORDER BY next_due_at ASC
LIMIT $2
`

type ListDueSubscriptionsParams struct {
	NextDueAt pgtype.Timestamptz `json:"next_due_at"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListDueSubscriptions(ctx context.Context, arg ListDueSubscriptionsParams) ([]Subscriptions, error) {
	rows, err := q.db.Query(ctx, listDueSubscriptions, arg.NextDueAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriptions
	for rows.Next() {
		var i Subscriptions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGraceExpiredSubscriptions = `-- name: ListGraceExpiredSubscriptions :many
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE status = 'past_due' AND grace_until IS NOT NULL AND grace_until <= $1
ORDER BY grace_until ASC
LIMIT $2
`

type ListGraceExpiredSubscriptionsParams struct {
	GraceUntil pgtype.Timestamptz `json:"grace_until"`
	Limit      int32              `json:"limit"`
}

func (q *Queries) ListGraceExpiredSubscriptions(ctx context.Context, arg ListGraceExpiredSubscriptionsParams) ([]Subscriptions, error) {
	rows, err := q.db.Query(ctx, listGraceExpiredSubscriptions, arg.GraceUntil, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriptions
	for rows.Next() {
		var i Subscriptions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByUserID = `-- name: ListSubscriptionsByUserID :many
SELECT id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at FROM subscriptions
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSubscriptionsByUserID(ctx context.Context, userID pgtype.UUID) ([]Subscriptions, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscriptions
	for rows.Next() {
		var i Subscriptions
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlanID,
			&i.Status,
			&i.BillingCycle,
			&i.PriceMinor,
			&i.Currency,
			&i.StartedAt,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextDueAt,
			&i.GraceUntil,
			&i.CancelAtPeriodEnd,
			&i.EndedAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewSubscription = `-- name: RenewSubscription :one
UPDATE subscriptions
SET status = 'active',
    current_period_start = $2,
    current_period_end = $3,
    next_due_at = $4,
    grace_until = NULL,
    version = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
`

type RenewSubscriptionParams struct {
	ID                 pgtype.UUID        `json:"id"`
	CurrentPeriodStart pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd   pgtype.Timestamptz `json:"current_period_end"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
}

func (q *Queries) RenewSubscription(ctx context.Context, arg RenewSubscriptionParams) (Subscriptions, error) {
	row := q.db.QueryRow(ctx, renewSubscription,
		arg.ID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextDueAt,
	)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setCancelAtPeriodEnd = `-- name: SetCancelAtPeriodEnd :one
UPDATE subscriptions
SET cancel_at_period_end = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
`

type SetCancelAtPeriodEndParams struct {
	ID                pgtype.UUID `json:"id"`
	CancelAtPeriodEnd bool        `json:"cancel_at_period_end"`
}

func (q *Queries) SetCancelAtPeriodEnd(ctx context.Context, arg SetCancelAtPeriodEndParams) (Subscriptions, error) {
	row := q.db.QueryRow(ctx, setCancelAtPeriodEnd, arg.ID, arg.CancelAtPeriodEnd)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET status = $2,
    ended_at = CASE WHEN $2 IN ('cancelled', 'expired', 'terminated') THEN now() ELSE ended_at END,
    version = version + 1,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, plan_id, status, billing_cycle, price_minor, currency, started_at, current_period_start, current_period_end, next_due_at, grace_until, cancel_at_period_end, ended_at, version, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscriptions, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus, arg.ID, arg.Status)
	var i Subscriptions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlanID,
		&i.Status,
		&i.BillingCycle,
		&i.PriceMinor,
		&i.Currency,
		&i.StartedAt,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextDueAt,
		&i.GraceUntil,
		&i.CancelAtPeriodEnd,
		&i.EndedAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
