// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
    id, user_id, currency, available_balance_minor, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, now(), now()
) RETURNING id, user_id, currency, available_balance_minor, created_at, updated_at
`

type CreateWalletParams struct {
	ID                    pgtype.UUID `json:"id"`
	UserID                pgtype.UUID `json:"user_id"`
	Currency              string      `json:"currency"`
	AvailableBalanceMinor int64       `json:"available_balance_minor"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallets, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.ID,
		arg.UserID,
		arg.Currency,
		arg.AvailableBalanceMinor,
	)
	var i Wallets
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByUserID = `-- name: GetWalletByUserID :one
SELECT id, user_id, currency, available_balance_minor, created_at, updated_at FROM wallets
WHERE user_id = $1 AND currency = $2 LIMIT 1
`

type GetWalletByUserIDParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Currency string      `json:"currency"`
}

func (q *Queries) GetWalletByUserID(ctx context.Context, arg GetWalletByUserIDParams) (Wallets, error) {
	row := q.db.QueryRow(ctx, getWalletByUserID, arg.UserID, arg.Currency)
	var i Wallets
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByUserIDForUpdate = `-- name: GetWalletByUserIDForUpdate :one
SELECT id, user_id, currency, available_balance_minor, created_at, updated_at FROM wallets
WHERE user_id = $1 AND currency = $2 LIMIT 1 FOR UPDATE
`

type GetWalletByUserIDForUpdateParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Currency string      `json:"currency"`
}

func (q *Queries) GetWalletByUserIDForUpdate(ctx context.Context, arg GetWalletByUserIDForUpdateParams) (Wallets, error) {
	row := q.db.QueryRow(ctx, getWalletByUserIDForUpdate, arg.UserID, arg.Currency)
	var i Wallets
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWalletBalance = `-- name: UpdateWalletBalance :one
UPDATE wallets
SET available_balance_minor = $3,
    updated_at = now()
WHERE user_id = $1 AND currency = $2
RETURNING id, user_id, currency, available_balance_minor, created_at, updated_at
`

type UpdateWalletBalanceParams struct {
	UserID                pgtype.UUID `json:"user_id"`
	Currency              string      `json:"currency"`
	AvailableBalanceMinor int64       `json:"available_balance_minor"`
}

func (q *Queries) UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) (Wallets, error) {
	row := q.db.QueryRow(ctx, updateWalletBalance, arg.UserID, arg.Currency, arg.AvailableBalanceMinor)
	var i Wallets
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Currency,
		&i.AvailableBalanceMinor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
